// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJNZBxw7L0AQm1wkehRodcC8T-qVRwqM0',
    appId: '1:115902229738:web:74bebf1b21ee563def3b93',
    messagingSenderId: '115902229738',
    projectId: 'avis-test-firebase',
    authDomain: 'avis-test-firebase.firebaseapp.com',
    storageBucket: 'avis-test-firebase.appspot.com',
    measurementId: 'G-14P5ZCBYBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPdvUnvDpzurLFt7FSzC5YWqyvs-tWf6A',
    appId: '1:115902229738:android:5dd8f8afe006e8dfef3b93',
    messagingSenderId: '115902229738',
    projectId: 'avis-test-firebase',
    storageBucket: 'avis-test-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjKeza6Dwd_9O0dUTYwDwsEiYKGIRrX38',
    appId: '1:115902229738:ios:fa67243056a41339ef3b93',
    messagingSenderId: '115902229738',
    projectId: 'avis-test-firebase',
    storageBucket: 'avis-test-firebase.appspot.com',
    iosClientId: '115902229738-k9ke7squg3f7olqck0jhdokt7cqoukh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjKeza6Dwd_9O0dUTYwDwsEiYKGIRrX38',
    appId: '1:115902229738:ios:fa67243056a41339ef3b93',
    messagingSenderId: '115902229738',
    projectId: 'avis-test-firebase',
    storageBucket: 'avis-test-firebase.appspot.com',
    iosClientId: '115902229738-k9ke7squg3f7olqck0jhdokt7cqoukh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
